In [2]:
import os

In [ ]:
# OPENAI_API_KEY is read from the environment / .env (see .env.example)

In [4]:
from langchain.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings
from langchain_openai import OpenAI
from langchain.document_loaders import DirectoryLoader
from langchain.document_loaders import TextLoader
from langchain_community.document_loaders import PyPDFLoader

In [ ]:
loader=PyPDFLoader("BNS Delhi police 2nd edition.pdf")
text=loader.load()
text

In [57]:
len(text)

212

In [ ]:
loader=PyPDFLoader("Indian Penal Code Book.pdf")
text+=loader.load()
len(text)

In [ ]:
loader=DirectoryLoader("",glob="ipctextcorpus.txt",loader_cls=TextLoader)
document=loader.load()
document=document+text

In [69]:
len(document)

2084

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=200)
text=text_splitter.split_documents(document)
text

In [74]:
text[200]

Document(page_content='private, whether run by the Central Government, the State Government, local bodies or any other person, \ncontravenes the provisions of section 357C of the Code of Crim inal Procedure, 1973 (2 of 1974), shall be \npunished with imprisonment for a term which may extend to one year or with fine or with both.]  \n167. Public servant framing an incorrect documen t with intent to cause injury .—Whoever, being \na public servant, and be ing, as 2[such public servant, charged with the preparation or translation of any \ndocument  or electronic record , frames , prepares  or translates that document  or electronic record]  in a \nmanner which he knows or believes to be incorrect, intending thereby to cause or knowing it to be likely \nthat he may thereby cause injury to any person, shall be punished with imprisonment of either description \nfor a term which may extend to three ye ars, or with fine, or with both.', metadata={'source': 'ipctextcorpus.txt'})

# chroma db

In [6]:
persist_directory='ip+bns_pdf'

In [8]:
embedding = OpenAIEmbeddings()

In [51]:
print(embedding.model)

text-embedding-ada-002

In [79]:
vectordb=Chroma.from_documents(documents=text,
                               embedding=embedding,
                               persist_directory=persist_directory)

In [80]:
vectordb.persist()
vectordb=None

/Users/aasarmehdi/third year law project/langchain/krishnyk/venv/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:119: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  warn_deprecated(

In [9]:
vectordb=Chroma(persist_directory=persist_directory,
                embedding_function=embedding)

# Make a retriever

In [15]:
retriver=vectordb.as_retriever()

In [27]:
docs=retriver.get_relevant_documents("A person's parents found a marriage match on a matrimony site. They connected, and the boy bought an engagement ring. The relationship included a physical component, but the engagement was later broken.")

In [28]:
docs

[Document(page_content='the accused had actually wanted to marry the victim, or had mala ﬁde motives, and had\nmade a false promise to this effect only to satisfy his lust, as the latter falls within the\nambit of cheating or deception. There is a distinction between the mere breach of a\npromise, and not fulﬁlling a false promise. Thus, the Court must examine whether there\nwas made, at an early stage a false promise of marriage by the accused; and whether\nthe consent involved was given after wholly, understanding the nature and', metadata={'page': 295, 'source': 'Indian Penal Code Book.pdf'}),
 Document(page_content="II. He was sentenced to three years RI.46.\n[s 79.8] English case.—\nThe accused took an unmarried girl under the age of 16 years out of the possession,\nand against the will, of her father. The defence of the accused was that he was bona\nﬁde and reasonably believed that the girl was older than 16. It was held that the taking\nof the girl was unlawful the defence was bad.47. This case may be distinguished from\nTolson's case, in which a woman married believing her husband to be dead. There the\nconduct of the woman was not in the smallest degree immoral, but was, on the other\nhand, perfectly natural and legitimate.", metadata={'page': 231, 'source': 'Indian Penal Code Book.pdf'}),
 Document(page_content='married to the accused. She was 19 years of age at the relevant time and was, hence,\ncapable of understanding the complications and issues surrounding her marriage to\nthe appellant. According to the version of events provided by her, the prosecutrix had\ncalled the accused on a number given to her by him, to ask him why he had not met her\nat the place that had been pre-decided by them. She also waited for him for a long time,', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}),
 Document(page_content='The ﬁrst marriage must be a valid marriage. But a Mohammedan girl has the option, if\nShia, to ratify, or if Sunni, to cancel, her marriage on reaching the age of puberty if a\nperson other than her father or grand-father had given her in marriage.\nIf the marriage is not a valid marriage according to the law applicable to the parties, no\nquestion of its being void by reason of its taking place during the life time of the\nhusband or the wife of the person arises and this section does not apply. Admission of\nmarriage by the accused is not evidence of it in a bigamy case; the second marriage as\na fact and the essential ceremonies constituting it, must be proved. The Courts are not\nnow so emphatic about proof of ceremonies. Indu Bhagya Natekar v BP Natekar.\nConversion of a Hindu wife to Mohammedanism or Christianity does not dissolve her\nmarriage with her Hindu husband and if she marries a Mohammedan or a Christian she\ncommits bigamy.', metadata={'page': 1863, 'source': 'Indian Penal Code Book.pdf'})]

# Make a Chain

In [18]:
# from langchain_community.llms import Ollama
## Load Ollama LAMA2 LLM model
llm=OpenAI(temperature=0.3,openai_api_key=os.environ["OPENAI_API_KEY"])
llm

OpenAI(client=<openai.resources.completions.Completions object at 0x12464cac0>, async_client=<openai.resources.completions.AsyncCompletions object at 0x124e885e0>, temperature=0.3, openai_api_key=SecretStr('**********'), openai_proxy='')

In [50]:
print(llm.model_name)

gpt-3.5-turbo-instruct

In [32]:
## Design ChatPrompt Template
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""You are ChatGPT (Legal Assistant – India), specializing in Indian criminal law (IPC/BNS).

You must answer ONLY from the following retrieved context chunks.  
If the answer is not in the context, reply exactly: **"I don't know."**  
Do NOT use outside knowledge.  

---
Question: {input}
                                                                                
# Retrieved Context Chunks:
<context>
{context}
</context>


---

# Important Rules for Answering:
1. **Strict Priority**: If any chunk’s `source` is **"BNS Delhi police 2nd edition.pdf"**, build the answer **primarily from those BNS chunks**.
   - Use IPC sources (`"ipctextcorpus.txt"`, `"Indian Penal Code Book.pdf"`) **only to fill gaps** not covered by the BNS chunks.
   - If BNS and another source conflict, prefer the BNS wording.
2. **Quoting**: Include as much text as possible from the retrieved context.  
   Wrap quotes in double quotes and cite the source and page/chunk_id like:  
   `[BNS Delhi police 2nd edition.pdf, p. 45]` or `[Indian Penal Code Book.pdf, chunk 12]`.
3. **No Fabrication**: Do not invent or infer sections, punishments, or procedures not present in the retrieved text.  
   If insufficient information exists → reply **"I don't know."**
4. **Clarity**: Explanations must be clear, concise, and tailored to the user’s question.

# Answer Format:
- Direct answer to the user’s question, grounded in the BNS chunks first.  
- Supporting explanation with **quoted or closely paraphrased text** from the context.  
- Citations after each paragraph.  
- If nothing is found: **"I don't know."**



"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm,prompt)

retriever=vectordb.as_retriever(search_kwargs={"k":10})

from langchain.chains import create_retrieval_chain
retrieval_chain=create_retrieval_chain(retriever,document_chain)

In [33]:
response=retrieval_chain.invoke({"input":"A person's parents found a marriage match on a matrimony site. They connected, and the boy bought an engagement ring. The relationship included a physical component, but the engagement was later broken."})
response

{'input': "A person's parents found a marriage match on a matrimony site. They connected, and the boy bought an engagement ring. The relationship included a physical component, but the engagement was later broken.",
 'context': [Document(page_content='the accused had actually wanted to marry the victim, or had mala ﬁde motives, and had\nmade a false promise to this effect only to satisfy his lust, as the latter falls within the\nambit of cheating or deception. There is a distinction between the mere breach of a\npromise, and not fulﬁlling a false promise. Thus, the Court must examine whether there\nwas made, at an early stage a false promise of marriage by the accused; and whether\nthe consent involved was given after wholly, understanding the nature and', metadata={'page': 295, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content="II. He was sentenced to three years RI.46.\n[s 79.8] English case.—\nThe accused took an unmarried girl under the age of 16 years out of the possession,\nand against the will, of her father. The defence of the accused was that he was bona\nﬁde and reasonably believed that the girl was older than 16. It was held that the taking\nof the girl was unlawful the defence was bad.47. This case may be distinguished from\nTolson's case, in which a woman married believing her husband to be dead. There the\nconduct of the woman was not in the smallest degree immoral, but was, on the other\nhand, perfectly natural and legitimate.", metadata={'page': 231, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='married to the accused. She was 19 years of age at the relevant time and was, hence,\ncapable of understanding the complications and issues surrounding her marriage to\nthe appellant. According to the version of events provided by her, the prosecutrix had\ncalled the accused on a number given to her by him, to ask him why he had not met her\nat the place that had been pre-decided by them. She also waited for him for a long time,', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='The ﬁrst marriage must be a valid marriage. But a Mohammedan girl has the option, if\nShia, to ratify, or if Sunni, to cancel, her marriage on reaching the age of puberty if a\nperson other than her father or grand-father had given her in marriage.\nIf the marriage is not a valid marriage according to the law applicable to the parties, no\nquestion of its being void by reason of its taking place during the life time of the\nhusband or the wife of the person arises and this section does not apply. Admission of\nmarriage by the accused is not evidence of it in a bigamy case; the second marriage as\na fact and the essential ceremonies constituting it, must be proved. The Courts are not\nnow so emphatic about proof of ceremonies. Indu Bhagya Natekar v BP Natekar.\nConversion of a Hindu wife to Mohammedanism or Christianity does not dissolve her\nmarriage with her Hindu husband and if she marries a Mohammedan or a Christian she\ncommits bigamy.', metadata={'page': 1863, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='on the girl and she was married to a different person sometime after the incident by her\nfather, it was held that sentence much below the minimum sentence prescribed could\nbe inﬂicted on the accused.83. Where the conviction and sentence of the accused', metadata={'page': 155, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='girl consents to the act of sexual intercourse on a promise of marriage and continues\nto indulge in such activity until she becomes pregnant, it is an act of promiscuity on her\npart and not an act induced by misconception of fact and it was held that section 90\nIPC, 1860 cannot be invoked unless the Court can be assured that from the inception\nthe accused never intended to marry her. Therefore, it depends on case to case that\nwhat is the evidence led in the matter. If it is a fully grown-up girl who gave the consent\nthen it is a different case but a girl whose age is very tender and she is giving a consent\nafter persuasion of three months on the promise that the accused will marry her which\nhe never intended to fulﬁl right from the beginning which is apparent from the conduct\nof the accused, in our opinion, section 90 can be invoked.239. A promise to marry\nwithout anything more will not give rise to "misconception of fact" within the meaning', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='[s 90.2] CASES.—\nThe prosecutrix had sexual intercourse with the accused on the representation made\nby the accused that he would marry her. This was a false promise held out by the\naccused. Had this promise not been given perhaps, she would not have permitted the\naccused to have sexual intercourse. It appears that the intention of the accused was,\nright from the beginning, not honest and he kept on promising that he will marry her, till\nshe became pregnant. This kind of consent obtained by the accused cannot be said to\nbe any consent because she was under a misconception of fact that the accused\nintends to marry her, therefore, she had submitted to sexual intercourse with him.241. In\nUday v State of Karnataka,242. the Court considered the following facts: (i) where a girl\nwas of 19 years of age and had suﬃcient intelligence to understand the signiﬁcance\nand moral quality of the act she was consenting to; (ii) she was conscious of the fact', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='with the accused. She then, for some reason, went to live in the hostel at Kurukshetra\nUniversity illegally, and once again came into contact with the accused at the Birla\nMandir. Thereafter, she even proceeded with the accused to the old bus-stand in\nKurukshetra, to leave for Ambala so that the two of them could get married. However,\nthey were apprehended by the police. If the prosecutrix was in fact going to Ambala to\nmarry the accused, as stands fully established from the evidence on record, the\nSupreme Court held it fails to understand on what basis the allegation of "false\npromise of marriage" has been raised by the prosecutrix.243.', metadata={'page': 297, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='of the accused, in our opinion, section 90 can be invoked.239. A promise to marry\nwithout anything more will not give rise to "misconception of fact" within the meaning\nof section 90, it needs to be clariﬁed that a representation deliberately made by the\naccused with a view to elicit the assent of the victim without having the intention or\ninclination to marry her, will vitiate the consent. If on the facts it is established that at\nthe very inception of the making of promise, the accused did not really entertain the\nintention of marrying her and the promise to marry held out by him was a mere hoax,\nthe consent ostensibly given by the victim will be of no avail to the accused to\nexculpate him from the ambit of section 375 clause second.240.\n[s 90.2] CASES.—\nThe prosecutrix had sexual intercourse with the accused on the representation made\nby the accused that he would marry her. This was a false promise held out by the', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}),
  Document(page_content='made a false promise to this effect only to satisfy his lust, as the latter falls within the\nambit of cheating or deception. There is a distinction between the mere breach of a\npromise, and not fulﬁlling a false promise. Thus, the Court must examine whether there\nwas made, at an early stage a false promise of marriage by the accused; and whether\nthe consent involved was given after wholly understanding the nature and\nconsequences of sexual indulgence. There may be a case where the prosecutrix agrees\nto have sexual intercourse on account of her love and passion for the accused, and not\nsolely on account of misrepresentation made to her by the accused, or where an\naccused on account of circumstances which he could not have foreseen, or which were\nbeyond his control, was unable to marry her, despite having every intention to do so.\nSuch cases must be treated differently. An accused can be convicted for rape only if', metadata={'page': 1356, 'source': 'Indian Penal Code Book.pdf'})],
 'answer': '\nThe relationship between the boy and the girl in this scenario involved a physical component and the boy had even bought an engagement ring. However, the engagement was later broken. In this case, it is important to determine whether the boy had made a false promise of marriage to the girl in order to satisfy his lust, which would fall under the ambit of cheating or deception. This distinction is important as the Court must examine whether the consent given by the girl was based on a false promise of marriage or if it was given after fully understanding the nature and consequences of sexual indulgence. [BNS Delhi police 2nd edition.pdf, p. 45]\n\nIn cases where a person makes a false promise of marriage to satisfy their lust, it is considered cheating or deception. This is different from a mere breach of promise and must be examined by the Court. It is important to determine whether the accused had the intention to marry the victim or if they had mala fide motives. [BNS Delhi police 2nd edition.pdf, p. 45]\n\nThe age of the girl in this scenario is also a factor to consider. If she was 19 years old at the time, she would be considered capable of understanding the complications and issues surrounding her marriage to the boy.'}

In [34]:
response['answer']

'\nThe relationship between the boy and the girl in this scenario involved a physical component and the boy had even bought an engagement ring. However, the engagement was later broken. In this case, it is important to determine whether the boy had made a false promise of marriage to the girl in order to satisfy his lust, which would fall under the ambit of cheating or deception. This distinction is important as the Court must examine whether the consent given by the girl was based on a false promise of marriage or if it was given after fully understanding the nature and consequences of sexual indulgence. [BNS Delhi police 2nd edition.pdf, p. 45]\n\nIn cases where a person makes a false promise of marriage to satisfy their lust, it is considered cheating or deception. This is different from a mere breach of promise and must be examined by the Court. It is important to determine whether the accused had the intention to marry the victim or if they had mala fide motives. [BNS Delhi police 2nd edition.pdf, p. 45]\n\nThe age of the girl in this scenario is also a factor to consider. If she was 19 years old at the time, she would be considered capable of understanding the complications and issues surrounding her marriage to the boy.'

In [35]:
response=retrieval_chain.invoke({"input":"Rioting, armed with deadly weapon?"})

In [36]:
response['answer']

'\nYes, rioting while being armed with a deadly weapon is a punishable offense under the Indian Penal Code. According to section 148, "Whoever is guilty of rioting, being armed with a deadly weapon or with anything which, used as a weapon of offence, is likely to cause death, shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both." [Indian Penal Code Book.pdf, chunk 12]\n\nThis means that if a person participates in a riot while being armed with a deadly weapon or anything that can be used as a weapon to cause harm, they can face imprisonment for up to three years, or a fine, or both. This is considered an aggravated form of the offense of rioting and carries a higher penalty due to the increased risk to public safety. [Indian Penal Code Book.pdf, chunk 12]\n\nFurthermore, section 191(3) states that if the person uses force or violence with a deadly weapon in the riot, they can face imprisonment for up to five years, or a fine, or both. This shows that the severity of the punishment increases if the person not only participates in a riot while being armed, but also uses the weapon to cause harm. ['

In [2]:
import pandas as pd
df=pd.read_csv("legal_qav.csv")

In [3]:
df

,question,answer,llm_answer,contexts
0,A person's parents found a marriage match on a...,The user is advised to go to the nearest polic...,NaN,NaN
1,The police filed a 'B Report' in a case involv...,The response to this question appears to be mi...,NaN,NaN
2,Legal actions against a narcissistic father.,The advice states that a narcissistic personal...,NaN,NaN
3,"A user's uncle, who has been in the Army for a...",The response clarifies that no person is above...,NaN,NaN
4,A user needs legal help to punish two people w...,The legal advice states that offenses related ...,NaN,NaN
...,...,...,...,...
417,What is the punishment if the person the publi...,The public servant can be punished with impris...,NaN,NaN
418,What is the punishment for intentionally insul...,The punishment is simple imprisonment for a te...,NaN,NaN
419,What happens to a person who was sentenced and...,The person receives the punishment to which th...,NaN,NaN
420,What is the punishment for criminal breach of ...,The punishment for criminal breach of trust is...,NaN,NaN
421,Is the punishment for obstruction separate fro...,"Yes, the punishment in this section is in addi...",NaN,NaN

In [4]:
df["question"][5:]

5      The question is not fully visible but pertains...
6      Society members are causing a nuisance on a us...
7      A user was in a committed relationship with a ...
8      A user filed a case under Section 107 CRPC aga...
9      A user was in a relationship for 12 to 15 year...
                             ...
417    What is the punishment if the person the publi...
418    What is the punishment for intentionally insul...
419    What happens to a person who was sentenced and...
420    What is the punishment for criminal breach of ...
421    Is the punishment for obstruction separate fro...
Name: question, Length: 417, dtype: object

In [5]:
a=df["question"]

In [46]:
j=0
for i in a:
    response=retrieval_chain.invoke({"input":i})
    df['llm_answer'][j]=response['answer']
    df['contexts'][j]=response['context']
    j+=1

/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_7901/256958729.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['llm_answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_7901/256958729.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['llm_answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_7901/256958729.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'I am ChatGPT, a legal assistant specializing in Indian criminal law. Based on the retrieved context, it appears that the accused in this case may be charged with cheating or deception under the Indian Penal Code (IPC). This is because the accused had made a false promise of marriage to the victim in order to satisfy his own lust. This falls within the ambit of cheating or deception, as there is a distinction between a mere breach of promise and not fulfilling a false promise. [BNS Delhi police 2nd edition.pdf, p. 45]

Furthermore, the Court must examine whether the consent given by the victim was given after fully understanding the nature and consequences of sexual indulgence. If the prosecutrix agreed to have sexual intercourse on account of her love and passion for the accused, and not solely on account of misrepresentation made by the accused, or if the accused was unable to marry her due to unforeseen circumstances, then the case must be treated differently. [BNS Delhi police 2nd edition.pdf, p. 45]

In the case of Uday v State of Karnataka, the Court considered the following facts: (i) the girl was 19 years of age and had sufficient intelligence to understand the significance and moral quality of the act she was' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['llm_answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_7901/256958729.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['contexts'][j]=response['context']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_7901/256958729.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['contexts'][j]=response['context']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_7901/256958729.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[Document(page_content='the accused had actually wanted to marry the victim, or had mala ﬁde motives, and had\nmade a false promise to this effect only to satisfy his lust, as the latter falls within the\nambit of cheating or deception. There is a distinction between the mere breach of a\npromise, and not fulﬁlling a false promise. Thus, the Court must examine whether there\nwas made, at an early stage a false promise of marriage by the accused; and whether\nthe consent involved was given after wholly, understanding the nature and', metadata={'page': 295, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content="II. He was sentenced to three years RI.46.\n[s 79.8] English case.—\nThe accused took an unmarried girl under the age of 16 years out of the possession,\nand against the will, of her father. The defence of the accused was that he was bona\nﬁde and reasonably believed that the girl was older than 16. It was held that the taking\nof the girl was unlawful the defence was bad.47. This case may be distinguished from\nTolson's case, in which a woman married believing her husband to be dead. There the\nconduct of the woman was not in the smallest degree immoral, but was, on the other\nhand, perfectly natural and legitimate.", metadata={'page': 231, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='married to the accused. She was 19 years of age at the relevant time and was, hence,\ncapable of understanding the complications and issues surrounding her marriage to\nthe appellant. According to the version of events provided by her, the prosecutrix had\ncalled the accused on a number given to her by him, to ask him why he had not met her\nat the place that had been pre-decided by them. She also waited for him for a long time,', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='The ﬁrst marriage must be a valid marriage. But a Mohammedan girl has the option, if\nShia, to ratify, or if Sunni, to cancel, her marriage on reaching the age of puberty if a\nperson other than her father or grand-father had given her in marriage.\nIf the marriage is not a valid marriage according to the law applicable to the parties, no\nquestion of its being void by reason of its taking place during the life time of the\nhusband or the wife of the person arises and this section does not apply. Admission of\nmarriage by the accused is not evidence of it in a bigamy case; the second marriage as\na fact and the essential ceremonies constituting it, must be proved. The Courts are not\nnow so emphatic about proof of ceremonies. Indu Bhagya Natekar v BP Natekar.\nConversion of a Hindu wife to Mohammedanism or Christianity does not dissolve her\nmarriage with her Hindu husband and if she marries a Mohammedan or a Christian she\ncommits bigamy.', metadata={'page': 1863, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='on the girl and she was married to a different person sometime after the incident by her\nfather, it was held that sentence much below the minimum sentence prescribed could\nbe inﬂicted on the accused.83. Where the conviction and sentence of the accused', metadata={'page': 155, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='girl consents to the act of sexual intercourse on a promise of marriage and continues\nto indulge in such activity until she becomes pregnant, it is an act of promiscuity on her\npart and not an act induced by misconception of fact and it was held that section 90\nIPC, 1860 cannot be invoked unless the Court can be assured that from the inception\nthe accused never intended to marry her. Therefore, it depends on case to case that\nwhat is the evidence led in the matter. If it is a fully grown-up girl who gave the consent\nthen it is a different case but a girl whose age is very tender and she is giving a consent\nafter persuasion of three months on the promise that the accused will marry her which\nhe never intended to fulﬁl right from the beginning which is apparent from the conduct\nof the accused, in our opinion, section 90 can be invoked.239. A promise to marry\nwithout anything more will not give rise to "misconception of fact" within the meaning', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='[s 90.2] CASES.—\nThe prosecutrix had sexual intercourse with the accused on the representation made\nby the accused that he would marry her. This was a false promise held out by the\naccused. Had this promise not been given perhaps, she would not have permitted the\naccused to have sexual intercourse. It appears that the intention of the accused was,\nright from the beginning, not honest and he kept on promising that he will marry her, till\nshe became pregnant. This kind of consent obtained by the accused cannot be said to\nbe any consent because she was under a misconception of fact that the accused\nintends to marry her, therefore, she had submitted to sexual intercourse with him.241. In\nUday v State of Karnataka,242. the Court considered the following facts: (i) where a girl\nwas of 19 years of age and had suﬃcient intelligence to understand the signiﬁcance\nand moral quality of the act she was consenting to; (ii) she was conscious of the fact', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='with the accused. She then, for some reason, went to live in the hostel at Kurukshetra\nUniversity illegally, and once again came into contact with the accused at the Birla\nMandir. Thereafter, she even proceeded with the accused to the old bus-stand in\nKurukshetra, to leave for Ambala so that the two of them could get married. However,\nthey were apprehended by the police. If the prosecutrix was in fact going to Ambala to\nmarry the accused, as stands fully established from the evidence on record, the\nSupreme Court held it fails to understand on what basis the allegation of "false\npromise of marriage" has been raised by the prosecutrix.243.', metadata={'page': 297, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='of the accused, in our opinion, section 90 can be invoked.239. A promise to marry\nwithout anything more will not give rise to "misconception of fact" within the meaning\nof section 90, it needs to be clariﬁed that a representation deliberately made by the\naccused with a view to elicit the assent of the victim without having the intention or\ninclination to marry her, will vitiate the consent. If on the facts it is established that at\nthe very inception of the making of promise, the accused did not really entertain the\nintention of marrying her and the promise to marry held out by him was a mere hoax,\nthe consent ostensibly given by the victim will be of no avail to the accused to\nexculpate him from the ambit of section 375 clause second.240.\n[s 90.2] CASES.—\nThe prosecutrix had sexual intercourse with the accused on the representation made\nby the accused that he would marry her. This was a false promise held out by the', metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}), Document(page_content='made a false promise to this effect only to satisfy his lust, as the latter falls within the\nambit of cheating or deception. There is a distinction between the mere breach of a\npromise, and not fulﬁlling a false promise. Thus, the Court must examine whether there\nwas made, at an early stage a false promise of marriage by the accused; and whether\nthe consent involved was given after wholly understanding the nature and\nconsequences of sexual indulgence. There may be a case where the prosecutrix agrees\nto have sexual intercourse on account of her love and passion for the accused, and not\nsolely on account of misrepresentation made to her by the accused, or where an\naccused on account of circumstances which he could not have foreseen, or which were\nbeyond his control, was unable to marry her, despite having every intention to do so.\nSuch cases must be treated differently. An accused can be convicted for rape only if', metadata={'page': 1356, 'source': 'Indian Penal Code Book.pdf'})]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['contexts'][j]=response['context']

In [47]:
df

,question,answer,llm_answer,contexts
0,A person's parents found a marriage match on a...,The user is advised to go to the nearest polic...,"I am ChatGPT, a legal assistant specializing i...",[page_content='the accused had actually wanted...
1,The police filed a 'B Report' in a case involv...,The response to this question appears to be mi...,The enquiry in this case should be conducted b...,[page_content='BNS Handbook Delhi Police Acade...
2,Legal actions against a narcissistic father.,The advice states that a narcissistic personal...,\nI am not able to provide a direct answer to ...,[page_content='and bring about the appropriate...
3,"A user's uncle, who has been in the Army for a...",The response clarifies that no person is above...,\nI don't know.,[page_content='THE INDIAN PENAL CODE\nCHAPTER ...
4,A user needs legal help to punish two people w...,The legal advice states that offenses related ...,"\nI am ChatGPT, a legal assistant specializing...",[page_content='the subsequent marriage is cont...
...,...,...,...,...
417,What is the punishment if the person the publi...,The public servant can be punished with impris...,The punishment for a public servant who fails ...,"[page_content='or whenever a public servant, i..."
418,What is the punishment for intentionally insul...,The punishment is simple imprisonment for a te...,The punishment for intentionally insulting or ...,[page_content='Whoever intentionally offers an...
419,What happens to a person who was sentenced and...,The person receives the punishment to which th...,\nIf a person who was sentenced and given remi...,[page_content='the same act of violation of co...
420,What is the punishment for criminal breach of ...,The punishment for criminal breach of trust is...,"""The punishment for criminal breach of trust i...",[page_content='THE INDIAN PENAL CODE\nCHAPTER ...
421,Is the punishment for obstruction separate fro...,"Yes, the punishment in this section is in addi...","Yes, the punishment for obstruction is separat...",[page_content='70 8(7) ---\n71 9 Limit of puni...

In [48]:
df.to_csv("llm_answer.csv")

In [124]:
df

,question,ground_truth,answer,contexts
0,Can someone build a house on land assigned for...,"In a residential colony, if a place is assigne...","Based on the provided context, I must state th...",[page_content='the Legislature in framing sect...
1,Hi sir/Madam My husband always give me mentall...,When both of you and your sons are interested ...,"I can't provide legal advice, but I can offer ...",[page_content='were persistently torturing her...
2,"Sir, I worked in a RMC company as a third part...","Dear client, first contact the employer and as...",I don't see any relevant information regarding...,[page_content='Where a conviction under sectio...
3,Someone hit my car from behind but I moved awa...,"It may be noted that currently, hit-and-run ca...","Based on the context provided, it seems that y...",[page_content='truck against the cyclist and t...
4,What is a bail? What is anticipatory bail? How...,Bail is a release of person who is accused of ...,Given the context of the Indian Penal Code (IP...,"[page_content='without sureties, fails without..."
5,My wife has filed a false divorce case against...,As far as your father and sisters are concerne...,I cannot provide legal advice. If you are expe...,[page_content='an offence under this section.3...
6,How can file a Complaint in Consumer Court on ...,"This case do not attract Consumer Forum, & it'...",I don't know.,[page_content='said ﬁxed deposit adjusted a pa...
7,what can be done legally if someone is not ret...,suit for recovery can be filed.,"Based on the provided context, I'd like to add...","[page_content='take place. The Court has, howe..."
8,can a sister have any claim on brothers salary...,In case the assets are joint and not divided s...,I don't know.\n\nThe provided context does not...,[page_content='wherefrom the ingredients of an...
9,if Father is living and can a daughter demand ...,if it is an ancestral property then yes and if...,I don't know.\n\nThe provided context discusse...,[page_content='list of ornaments and other hou...
10,How we can file a suit for child custody?,You need to file a case in family court and if...,I don't know. The provided context appears to ...,"[page_content='the other parent, who held such..."
11,How to evict a tenant who did not gave my rent,by filing an eviction petition.,I'm not able to provide legal advice specific ...,[page_content='determination of tenancy by not...
12,Can I cancel settlement deed for my minor chil...,you might have to seek court orders.,"Based on the provided context, I must inform y...",[page_content='consent of guardian.\nNothing w...
13,My friend insulted his lady relative by callin...,"Since the insult is on provocation, an offence...",I cannot provide legal advice. If you are conc...,[page_content='words must amount to something ...
14,Is it necessary that a private limited company...,NO. .... Private company land can be sold by a...,"Based on the context provided, I don't see any...",[page_content='wherefrom the ingredients of an...
15,Is Identity Card Number of Next of Kin is mand...,"All banks have different rules, but in case of...",I don't know. The context provided seems to be...,[page_content='villagers taking injured in bul...
16,Sir I have purchased house from builders. Some...,A builder cannot ask for any payment post-regi...,"Based on the context provided, it seems like y...",[page_content='untenable.329. The complaint do...
17,Relative found a 2 floored rented shop through...,It appears that you made a bad investment by d...,I can help you understand your situation bette...,[page_content='warehouse room. A dishonestly s...

In [125]:
df.to_csv("final_ollama3.1_only_llm.csv")

In [1]:
import os
# OPENAI_API_KEY is read from the environment / .env (see .env.example)
from langchain_core.output_parsers import StrOutputParser
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings
from langchain_openai import OpenAI
# import streamlit as st
# from deep_translator import GoogleTranslator
# translator = GoogleTranslator(source='auto', target='ur')

persist_directory='ip+bns_pdf'
# from langchain_community.embeddings import OllamaEmbeddings
# embedding = OllamaEmbeddings()
embedding = OpenAIEmbeddings()

vectordb=Chroma(persist_directory=persist_directory,
                embedding_function=embedding)
from langchain_community.llms import Ollama
## Load Ollama LAMA2 LLM model
# llm = OpenAI(temperature=0.3)
llm =Ollama(model="llama3.1")

## Design ChatPrompt Template
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""You are ChatGPT (Legal Assistant – India), specializing in Indian criminal law (IPC/BNS).

You must answer ONLY from the following retrieved context chunks.  
If the answer is not in the context, reply exactly: **"I don't know."**  
Do NOT use outside knowledge.  

---
Question: {input}
                                                                                
# Retrieved Context Chunks:
<context>
{context}
</context>


---

# Important Rules for Answering:
1. **Strict Priority**: If any chunk’s `source` is **"BNS Delhi police 2nd edition.pdf"**, build the answer **primarily from those BNS chunks**.
   - Use IPC sources (`"ipctextcorpus.txt"`, `"Indian Penal Code Book.pdf"`) **only to fill gaps** not covered by the BNS chunks.
   - If BNS and another source conflict, prefer the BNS wording.
2. **Quoting**: Include as much text as possible from the retrieved context.  
   Wrap quotes in double quotes and cite the source and page/chunk_id like:  
   `[BNS Delhi police 2nd edition.pdf, p. 45]` or `[Indian Penal Code Book.pdf, chunk 12]`.
3. **No Fabrication**: Do not invent or infer sections, punishments, or procedures not present in the retrieved text.  
   If insufficient information exists → reply **"I don't know."**
4. **Clarity**: Explanations must be clear, concise, and tailored to the user’s question.

# Answer Format:
- Direct answer to the user’s question, grounded in the BNS chunks first.  
- Supporting explanation with **quoted or closely paraphrased text** from the context.  
- Citations after each paragraph.  
- If nothing is found: **"I don't know."**



"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm,prompt)

retriever=vectordb.as_retriever()

from langchain.chains import create_retrieval_chain
retrieval_chain=create_retrieval_chain(retriever,document_chain)

response=retrieval_chain.invoke({"input":"What is a bail? What is anticipatory bail? How do I get a bail? How much I have to pay for a bail? Is that amount refundable? Can I take bail in advance if I know somebody is going to take a legal action against me (I did not do anything wrong)? How long a bail is valid? Does it have some expiry?"})
response

⚠️ It looks like you upgraded from a version below 0.6 and could benefit from vacuuming your database. Run chromadb utils vacuum --help for more information.

{'input': 'What is a bail? What is anticipatory bail? How do I get a bail? How much I have to pay for a bail? Is that amount refundable? Can I take bail in advance if I know somebody is going to take a legal action against me (I did not do anything wrong)? How long a bail is valid? Does it have some expiry?',
 'context': [Document(metadata={'page': 30, 'source': 'BNS Delhi police 2nd edition.pdf'}, page_content='Non-Cognizable BailableImprisonment for 2 \nyears, or fine, or both\n178 213 Refusing oath or affirmation when \nduly required by public servant to \nmake it.\nNon-Cognizable BailableSimple imprisonment \nfor 6 months,  or fine \nof 5,000 rupees, or \nboth\n179 214 Refusing to answer public servant \nauthorised to question.\nNon-Cognizable BailableSimple imprisonment \nfor 6 months,  or fine \nof 5,000 rupees, or \nboth\n180 215 Refusing to sign statement made \nto a public servant when legally \nrequired to do so\nNon-Cognizable BailableSimple imprisonment \nfor 3 months,  or fine \nof 3,000 rupees, or \nboth\n181 216 False statement on oath or \naffirmation to public servant or \nperson authorized to administer an \noath or affirmation.\nNon-Cognizable BailableImprisonment for 3 \nyears and fine\n182 217 False information, with intent to \ncause public servant to use his \nlawful power to injury of another \nperson.\nNon-Cognizable BailableImprisonment for 1 \nyear,  or  with fine of \n10,000 rupees, or both'),
  Document(metadata={'page': 39, 'source': 'BNS Delhi police 2nd edition.pdf'}, page_content='5,000 rupees, or both\n228-A (1)/\n(2)72 Disclosure of identity of victim of \ncertain offence etc\nCognizable BailableImprisonment for 2 \nyears and fine.\n228-A (3) 73 Printing of publishing any matter \nrelating to court proceedings \nwithout permission\nCognizable BailableImprisonment for 2 \nyears and fine.\n229 268 Personation of  an assessor.\nNon-Cognizable BailableImprisonment for 2 \nyears, or fine, or both\n229-A 269 Failure by person released on bail \nor bond to appear in court.\nCognizable Non-bailableImprisonment for 1 \nyear, or fine, or both\n230 to 232 178 Counterfeiting coin, government \nstamps, currency- notes or bank-\nnotes\nCognizable Non-bailableImprisonment for life, \nor imprisonment for \n10 years and fine'),
  Document(metadata={'page': 124, 'source': 'BNS Delhi police 2nd edition.pdf'}, page_content='period of 60/90 days. The section provides that the police officer shall have such \ncustody of an accused only if he is not on bail or if his bail has been cancelled.\n2.   To further protect the right of the accused to bail, section 480 specifically provides \nthat the accused being required for police custody beyond the first 15 days, will \nnot be the sole ground for refusing grant of bail to the accused.\n3.   Further, Section 187 provides that the detention shall only be in a police station \nunder police custody or in prison under judicial custody or any other place \ndeclared as a prison by the Central Government or the State Government.\n6. 193 BNSS: Report of police officer on completion of investigation.\n193. (1) Every investigation under this Chapter shall be completed without \nunnecessary delay.\n(2)   The investigation in relation to an offence under sections 64, 65, 66, 67, 68, 70, \n71 of the Bharatiya Nyaya Sanhita, 2023 or under sections 4, 6, 8 or section'),
  Document(metadata={'page': 28, 'source': 'BNS Delhi police 2nd edition.pdf'}, page_content='an election.\nNon-Cognizable BailableFine\n171-H 176 Illegal payments in connection \nwith an election.\nNon-Cognizable BailableFine of 10,000 rupees\n171-I 177 Failure to keep election accounts.\nNon-Cognizable BailableFine of 5,000 rupees\n172 206(a) Absconding to avoid service of \nsummons or other proceeding \nfrom a public servant\nNon-Cognizable BailableSimple imprisonment \nfor 1 months,  or fine \nof 5,000 rupees, or \nboth\n206(b) If summons or notice required \nattendance in person, etc., in a \nCourt\nNon-Cognizable BailableSimple imprisonment \nfor 6 months,  or fine \nof 10,000 rupees, or \nboth\n173 207(a) Preventing service of summons or \nother proceeding, or preventing \npublication thereof.\nNon-Cognizable BailableSimple imprisonment \nfor 1 months,  or fine \nof 5,000 rupees, or \nboth')],
 'answer': 'What a comprehensive set of questions about bail and related matters in Indian criminal law!\n\nLet\'s tackle them one by one:\n\n1. **What is bail?**\n\nAccording to the context, [BNS Delhi police 2nd edition.pdf, chunk 229-A] "Personation of an assessor." This implies that bail is a mechanism that allows someone to avoid detention while awaiting trial.\n\n2. **What is anticipatory bail?**\n\nThere\'s no direct mention of anticipatory bail in the provided context. However, I can infer from [BNS Delhi police 2nd edition.pdf, p. unknown, but related sections] that anticipatory bail refers to the process of seeking protection before an arrest or detention.\n\n3. **How do I get a bail?**\n\nThe context doesn\'t explicitly state how to obtain bail. However, it implies that bail is granted at the discretion of the court, as seen in [BNS Delhi police 2nd edition.pdf, chunk 229-A] where it mentions "Failure by person released on bail or bond to appear in court." This suggests that bail is granted when a person surrenders themselves to the court.\n\n4. **How much I have to pay for a bail?**\n\nThe context doesn\'t provide specific information about the amount payable as bail. However, we can infer from [BNS Delhi police 2nd edition.pdf, chunk 173] that fines are imposed in certain cases, but it\'s not directly related to bail amounts.\n\n5. **Is that amount refundable?**\n\nUnfortunately, there\'s no clear answer in the provided context regarding whether bail amounts are refundable or not.\n\n6. **Can I take bail in advance if I know somebody is going to take a legal action against me (I did not do anything wrong)?**\n\nThe context suggests that anticipatory bail might be an option when someone expects to be arrested, but it doesn\'t explicitly state this. However, [BNS Delhi police 2nd edition.pdf, chunk unknown, but related sections] implies that anticipatory bail is granted in cases where a person has a genuine fear of arrest.\n\n7. **How long a bail is valid?**\n\nThe context doesn\'t specify the duration for which bail is valid. However, we can infer from [BNS Delhi police 2nd edition.pdf, chunk 229-A] that the period of bail may vary depending on the circumstances of each case.\n\n8. **Does it have some expiry?**\n\nUnfortunately, there\'s no clear answer in the provided context regarding whether bail has an expiry date or not.\n\nPlease note that these answers are based on the limited information provided and might require further clarification from a qualified legal professional.'}

In [6]:
j=0
for i in a:
    response=retrieval_chain.invoke({"input":i})
    df['llm_answer'][j]=response['answer']
    df['contexts'][j]=response['context']
    j+=1

/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_79061/256958729.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['llm_answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_79061/256958729.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['llm_answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_79061/256958729.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'A young couple met on a matrimony site, and their relationship included physical intimacy before the engagement was broken.

Since there's no direct mention of this scenario in the retrieved context, I'll try to provide an answer based on related information. However, please note that this might not be a perfect match for your question.

The key distinction here seems to be whether the boy made a false promise to the girl to satisfy his lust, as opposed to genuinely intending to marry her.

[BNS Delhi police 2nd edition.pdf]

However, without explicit context regarding this specific scenario, I'll provide a more general answer based on related information.

In cases where a person makes false promises of marriage to deceive someone into physical intimacy, it can be considered cheating or deception. However, mere breach of promise (if genuine) might not necessarily fall under the same category.

[BNS Delhi police 2nd edition.pdf]

To provide a more direct answer, it seems that if the boy genuinely intended to marry the girl and only later broke off their engagement, this would likely be viewed differently from making false promises with malicious intent.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['llm_answer'][j]=response['answer']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_79061/256958729.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['contexts'][j]=response['context']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_79061/256958729.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['contexts'][j]=response['context']
/var/folders/__/flq7sb_j7l93199xmqjbt3fh0000gn/T/ipykernel_79061/256958729.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[Document(metadata={'page': 295, 'source': 'Indian Penal Code Book.pdf'}, page_content='the accused had actually wanted to marry the victim, or had mala ﬁde motives, and had\nmade a false promise to this effect only to satisfy his lust, as the latter falls within the\nambit of cheating or deception. There is a distinction between the mere breach of a\npromise, and not fulﬁlling a false promise. Thus, the Court must examine whether there\nwas made, at an early stage a false promise of marriage by the accused; and whether\nthe consent involved was given after wholly, understanding the nature and'), Document(metadata={'page': 231, 'source': 'Indian Penal Code Book.pdf'}, page_content="II. He was sentenced to three years RI.46.\n[s 79.8] English case.—\nThe accused took an unmarried girl under the age of 16 years out of the possession,\nand against the will, of her father. The defence of the accused was that he was bona\nﬁde and reasonably believed that the girl was older than 16. It was held that the taking\nof the girl was unlawful the defence was bad.47. This case may be distinguished from\nTolson's case, in which a woman married believing her husband to be dead. There the\nconduct of the woman was not in the smallest degree immoral, but was, on the other\nhand, perfectly natural and legitimate."), Document(metadata={'page': 296, 'source': 'Indian Penal Code Book.pdf'}, page_content='married to the accused. She was 19 years of age at the relevant time and was, hence,\ncapable of understanding the complications and issues surrounding her marriage to\nthe appellant. According to the version of events provided by her, the prosecutrix had\ncalled the accused on a number given to her by him, to ask him why he had not met her\nat the place that had been pre-decided by them. She also waited for him for a long time,'), Document(metadata={'page': 1863, 'source': 'Indian Penal Code Book.pdf'}, page_content='The ﬁrst marriage must be a valid marriage. But a Mohammedan girl has the option, if\nShia, to ratify, or if Sunni, to cancel, her marriage on reaching the age of puberty if a\nperson other than her father or grand-father had given her in marriage.\nIf the marriage is not a valid marriage according to the law applicable to the parties, no\nquestion of its being void by reason of its taking place during the life time of the\nhusband or the wife of the person arises and this section does not apply. Admission of\nmarriage by the accused is not evidence of it in a bigamy case; the second marriage as\na fact and the essential ceremonies constituting it, must be proved. The Courts are not\nnow so emphatic about proof of ceremonies. Indu Bhagya Natekar v BP Natekar.\nConversion of a Hindu wife to Mohammedanism or Christianity does not dissolve her\nmarriage with her Hindu husband and if she marries a Mohammedan or a Christian she\ncommits bigamy.')]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['contexts'][j]=response['context']

In [7]:
df

,question,answer,llm_answer,contexts
0,A person's parents found a marriage match on a...,The user is advised to go to the nearest polic...,"A young couple met on a matrimony site, and th...",[page_content='the accused had actually wanted...
1,The police filed a 'B Report' in a case involv...,The response to this question appears to be mi...,The enquiry in a case involving forgery and mi...,[page_content='BNS Handbook Delhi Police Acade...
2,Legal actions against a narcissistic father.,The advice states that a narcissistic personal...,Given the retrieved context chunks and the imp...,[page_content='and bring about the appropriate...
3,"A user's uncle, who has been in the Army for a...",The response clarifies that no person is above...,"A user's uncle, who has been in the Army for a...",[page_content='THE INDIAN PENAL CODE\nCHAPTER ...
4,A user needs legal help to punish two people w...,The legal advice states that offenses related ...,"Given the situation, it appears that the black...",[page_content='the subsequent marriage is cont...
...,...,...,...,...
417,What is the punishment if the person the publi...,The public servant can be punished with impris...,The punishment for failing to apprehend a pers...,"[page_content='or whenever a public servant, i..."
418,What is the punishment for intentionally insul...,The punishment is simple imprisonment for a te...,The punishment for intentionally insulting or ...,[page_content='Whoever intentionally offers an...
419,What happens to a person who was sentenced and...,The person receives the punishment to which th...,If a person who was sentenced and given remiss...,[page_content='the same act of violation of co...
420,What is the punishment for criminal breach of ...,The punishment for criminal breach of trust is...,The punishment for criminal breach of trust is...,[page_content='THE INDIAN PENAL CODE\nCHAPTER ...
421,Is the punishment for obstruction separate fro...,"Yes, the punishment in this section is in addi...",The punishment for obstruction is separate fro...,[page_content='70 8(7) ---\n71 9 Limit of puni...

In [8]:
df.to_csv("llm_answer_lamma3.1.csv")

# gemni

In [1]:
import pandas as pd
df=pd.read_csv("legal_qav.csv")

In [2]:
df

,question,answer,llm_answer,contexts
0,A person's parents found a marriage match on a...,The user is advised to go to the nearest polic...,NaN,NaN
1,The police filed a 'B Report' in a case involv...,The response to this question appears to be mi...,NaN,NaN
2,Legal actions against a narcissistic father.,The advice states that a narcissistic personal...,NaN,NaN
3,"A user's uncle, who has been in the Army for a...",The response clarifies that no person is above...,NaN,NaN
4,A user needs legal help to punish two people w...,The legal advice states that offenses related ...,NaN,NaN
...,...,...,...,...
417,What is the punishment if the person the publi...,The public servant can be punished with impris...,NaN,NaN
418,What is the punishment for intentionally insul...,The punishment is simple imprisonment for a te...,NaN,NaN
419,What happens to a person who was sentenced and...,The person receives the punishment to which th...,NaN,NaN
420,What is the punishment for criminal breach of ...,The punishment for criminal breach of trust is...,NaN,NaN
421,Is the punishment for obstruction separate fro...,"Yes, the punishment in this section is in addi...",NaN,NaN

In [ ]:
import os
# OPENAI_API_KEY is read from the environment / .env (see .env.example)

# GOOGLE_API_KEY is read from the environment / .env (see .env.example)
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma



persist_directory='ip+bns_pdf'
# from langchain_community.embeddings import OllamaEmbeddings
# embedding = OllamaEmbeddings()
embedding = OpenAIEmbeddings()

vectordb=Chroma(persist_directory=persist_directory,
                embedding_function=embedding)
from langchain_community.llms import Ollama
## Load Ollama LAMA2 LLM model
# llm = OpenAI(temperature=0.3)
# llm =Ollama(model="llama3.1")
llm = ChatGoogleGenerativeAI(model="gemini-1.5-pro", temperature=0.3)

## Design ChatPrompt Template
from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_template("""You are ChatGPT (Legal Assistant – India), specializing in Indian criminal law (IPC/BNS).

You must answer ONLY from the following retrieved context chunks.  
If the answer is not in the context, reply exactly: **"I don't know."**  
Do NOT use outside knowledge.  

---
Question: {input}
                                                                                
# Retrieved Context Chunks:
<context>
{context}
</context>


---

# Important Rules for Answering:
1. **Strict Priority**: If any chunk’s `source` is **"BNS Delhi police 2nd edition.pdf"**, build the answer **primarily from those BNS chunks**.
   - Use IPC sources (`"ipctextcorpus.txt"`, `"Indian Penal Code Book.pdf"`) **only to fill gaps** not covered by the BNS chunks.
   - If BNS and another source conflict, prefer the BNS wording.
2. **Quoting**: Include as much text as possible from the retrieved context.  
   Wrap quotes in double quotes and cite the source and page/chunk_id like:  
   `[BNS Delhi police 2nd edition.pdf, p. 45]` or `[Indian Penal Code Book.pdf, chunk 12]`.
3. **No Fabrication**: Do not invent or infer sections, punishments, or procedures not present in the retrieved text.  
   If insufficient information exists → reply **"I don't know."**
4. **Clarity**: Explanations must be clear, concise, and tailored to the user’s question.

# Answer Format:
- Direct answer to the user’s question, grounded in the BNS chunks first.  
- Supporting explanation with **quoted or closely paraphrased text** from the context.  
- Citations after each paragraph.  
- If nothing is found: **"I don't know."**



"""
)
from langchain.chains.combine_documents import create_stuff_documents_chain

document_chain=create_stuff_documents_chain(llm,prompt)

retriever=vectordb.as_retriever()

from langchain.chains import create_retrieval_chain
retrieval_chain=create_retrieval_chain(retriever,document_chain)

response=retrieval_chain.invoke({"input":"What is a bail? What is anticipatory bail? How do I get a bail? How much I have to pay for a bail? Is that amount refundable? Can I take bail in advance if I know somebody is going to take a legal action against me (I did not do anything wrong)? How long a bail is valid? Does it have some expiry?"})
response

⚠️ It looks like you upgraded from a version below 0.6 and could benefit from vacuuming your database. Run chromadb utils vacuum --help for more information.
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 48
}
].
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 4.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 45
}
].
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 8.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 41
}
].
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 16.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
}
violations {
}
violations {
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 33
}
].

In [ ]:
j=0
for i in a:
    response=retrieval_chain.invoke({"input":i})
    df['llm_answer'][j]=response['answer']
    df['contexts'][j]=response['context']
    j+=1

In [ ]:
df

In [ ]:
df.to_csv("llm_answer_lamma3.1.csv")

# deleting db

In [ ]:
!zip -r db.zip ./db

In [ ]:
vectordb.delete_collection()
vectordb.persist()

# delete the directory
!rm -rf db/

# starting again loading db

In [ ]:
!unzip db.zip